on:
  pull_request:
    branches:
      - main
name: Pull request workflow
jobs:
  validate_assetlists:
    name: Validate Chain Config schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JSON-Schema-Validator
        run: npm install -g ajv-cli

      - name: Validate Chain Config schema
        run: ./validate-chainconfig.sh
